version: '3'

services:
  asa-server:
    image: ipcintron/asa-dedicated-docker-linux:latest
    container_name: asa-dedicated-docker-linux
    restart: unless-stopped
    volumes:
      - /appdata/asa/asa:/appdata/asa/asa
      - /appdata/asa/bins/steamcmd:/home/wine/.steam
      #- ./appdata/asa/bins/asa:/appdata/asa/asa
      #- ./appdata/asa/bins/steamcmd:/home/wine/.steam
    ports:
     - "27016:27016/udp"
