#!/bin/bash
sudo mkdir -p appdata/asa/bins/asa
sudo mkdir -p appdata/asa/bins/steamcmd


#container executes server as 1000:1000
if [ "$(stat -c '%u' appdata)" != "1000" ]; then
    echo "Setting owner of appdata to UID 1000"
    sudo chown -R 1000:1000 appdata
fi

sudo docker-compose up -d 
sudo docker-compose logs -f